package com.planirovanie.service;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

/**
 * Application event log written to a SEPARATE PostgreSQL database ({@code app.audit.*}).
 * Fully isolated from the primary JPA datasource: owns its own connection pool and JDBC
 * template. Non-blocking (events are written on a background thread) and fail-safe — if the
 * audit database is unavailable, logging self-disables and the application keeps running.
 */
@Service
public class AuditService {

    private static final Logger log = LoggerFactory.getLogger(AuditService.class);

    @Value("${app.audit.enabled:true}")
    private boolean enabled;
    @Value("${app.audit.url:jdbc:postgresql://localhost:5432/planirovanie_audit}")
    private String url;
    @Value("${app.audit.username:planirovanie}")
    private String username;
    @Value("${app.audit.password:planirovanie}")
    private String password;
    @Value("${app.audit.driver-class-name:}")
    private String driver;

    private HikariDataSource ds;
    private JdbcTemplate jdbc;
    private ThreadPoolExecutor exec;

    private static final String DDL =
        "CREATE TABLE IF NOT EXISTS audit_events (" +
        " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        " ts TIMESTAMP, category VARCHAR(32), action VARCHAR(64)," +
        " username VARCHAR(128), role VARCHAR(32), method VARCHAR(8)," +
        " path VARCHAR(512), status INT, duration_ms INT," +
        " ip VARCHAR(64), user_agent VARCHAR(512), detail TEXT)";

    @PostConstruct
    public void init() {
        if (!enabled) { log.info("Audit logging disabled (app.audit.enabled=false)."); return; }
        try {
            HikariConfig cfg = new HikariConfig();
            cfg.setJdbcUrl(url);
            cfg.setUsername(username);
            cfg.setPassword(password);
            if (driver != null && !driver.isBlank()) cfg.setDriverClassName(driver);
            cfg.setPoolName("audit-pool");
            cfg.setMaximumPoolSize(2);
            cfg.setMinimumIdle(0);
            cfg.setConnectionTimeout(3000);
            cfg.setInitializationFailTimeout(3000);   // fail fast if the audit DB is unreachable
            ds = new HikariDataSource(cfg);
            jdbc = new JdbcTemplate(ds);
            jdbc.execute(DDL);
            try { jdbc.execute("CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_events (ts)"); } catch (Exception ignore) {}
            // bounded background writer; drop events if the queue is saturated (never block a request)
            exec = new ThreadPoolExecutor(1, 1, 30, TimeUnit.SECONDS,
                    new ArrayBlockingQueue<>(2000), r -> { Thread t = new Thread(r, "audit-writer"); t.setDaemon(true); return t; },
                    new ThreadPoolExecutor.DiscardPolicy());
            log.info("Audit logging enabled → {}", url);
        } catch (Exception e) {
            enabled = false; jdbc = null;
            if (ds != null) { try { ds.close(); } catch (Exception ignore) {} ds = null; }
            log.warn("Audit logging disabled — could not open audit database {} ({}). " +
                     "Create it (e.g. CREATE DATABASE planirovanie_audit) to enable.", url, e.getMessage());
        }
    }

    public boolean isEnabled() { return enabled && jdbc != null; }

    /** Queue one event for asynchronous insertion. Never throws. */
    public void log(String category, String action, String username, String role,
                    String method, String path, Integer status, Integer durationMs,
                    String ip, String userAgent, String detail) {
        if (!isEnabled() || exec == null) return;
        final Timestamp now = Timestamp.from(Instant.now());
        try {
            exec.submit(() -> {
                try {
                    jdbc.update("INSERT INTO audit_events" +
                            " (ts,category,action,username,role,method,path,status,duration_ms,ip,user_agent,detail)" +
                            " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
                            now, trim(category,32), trim(action,64), trim(username,128), trim(role,32),
                            trim(method,8), trim(path,512), status, durationMs, trim(ip,64),
                            trim(userAgent,512), detail);
                } catch (Exception ex) {
                    log.debug("audit insert failed: {}", ex.getMessage());
                }
            });
        } catch (Exception ignore) { /* executor rejected — drop */ }
    }

    /** Recent events, newest first, with optional category / username substring filters. */
    public List<Map<String, Object>> recent(int limit, String category, String user) {
        if (!isEnabled()) return List.of();
        int lim = Math.max(1, Math.min(limit, 1000));
        StringBuilder sql = new StringBuilder("SELECT id,ts,category,action,username,role,method,path,status,duration_ms,ip,user_agent,detail FROM audit_events");
        java.util.List<Object> args = new java.util.ArrayList<>();
        java.util.List<String> where = new java.util.ArrayList<>();
        if (category != null && !category.isBlank()) { where.add("category = ?"); args.add(category.trim().toUpperCase()); }
        if (user != null && !user.isBlank()) { where.add("LOWER(username) LIKE ?"); args.add("%" + user.trim().toLowerCase() + "%"); }
        if (!where.isEmpty()) sql.append(" WHERE ").append(String.join(" AND ", where));
        sql.append(" ORDER BY ts DESC, id DESC LIMIT ").append(lim);
        try { return jdbc.queryForList(sql.toString(), args.toArray()); }
        catch (Exception e) { return List.of(); }
    }

    public long count() {
        if (!isEnabled()) return 0;
        try { Long n = jdbc.queryForObject("SELECT COUNT(*) FROM audit_events", Long.class); return n == null ? 0 : n; }
        catch (Exception e) { return 0; }
    }

    private static String trim(String s, int max) { return (s == null || s.length() <= max) ? s : s.substring(0, max); }

    @PreDestroy
    public void close() {
        if (exec != null) { exec.shutdown(); try { exec.awaitTermination(2, TimeUnit.SECONDS); } catch (InterruptedException ignore) {} }
        if (ds != null) ds.close();
    }
}
